# Generated by Django 5.0.4 on 2024-11-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'Слово', 'verbose_name_plural': 'Слова'},
        ),
        migrations.AlterField(
            model_name='word',
            name='meaning',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
